### PR TITLE
[IDEA] Feat: Add color scheme switcher and option to hide KDE Connect 

### PR DESCRIPTION
**Pull request by DenysMb**
Hi!
This PR is just an idea of what could be done to make this widget even better.
The first idea is to add an option to hide KDE Connect. Some people don't use and, I don't think that this is a crucial item to be there, all the time, to everyone. So, we could just start with it disabled and, if the user want, enable it in the configuration.
The second idea is based on [this widget](https://store.kde.org/p/1804745) ([repo here](https://github.com/heqro/colorschemeswapper-plasmoid)). This is a very nice widget to select two color scheme to swap between. So, the user could select a light theme and a dark theme and just switch between them in a click of a button.
The problem with this second one is the bunch of code, it don't seem to me like very good so, we can remove this option to let the user select between the color scheme and just hardcode "BreezeLight" and "BreezeDark" there.

https://user-images.githubusercontent.com/33737137/194538837-763bab5f-d701-48de-9511-b0603f11c5a9.mp4

### CODE REVIEW

**Comment by Prayag2** [comment]
This is AMAZING!! I love the light and dark theme switchers! I'll test it at night and merge it!

**Comment by DenysMb** [comment]
I just did another commit because I was concerned about the code maintainability. I create a folder called "components" and put the code on ColorSchemeSwitcher.qml so, that way, we need only to import the "Components" and add there on "FullRepresentation.qml" as "Components.ColorSchemeSwitcher", controlling the visibility there.
It is just a "good practice", I think is good to let all the logic of a component/functionality in one place.

**Comment by Prayag2** [comment]
Could you please add the license too? I've created one right now.

**Comment by lsomm** [comment]
This looks great indeed! Gotta love it when someone just improves on an idea and the changes are getting merged back into master <3

**Comment by MenacingPerson** [comment]
> just hardcode "BreezeLight" and "BreezeDark" there.

Oooor... You could just let the user specify it... Or give an option to run a script when it's clicked

**Pull request merged**
