### PR TITLE
feat: initial cmake file

### PR DESCRIPTION
**Pull request by onuralpszr**
initial cmake file for system-wide installation and make easier for distros to package it

Signed-off-by: Onuralp SEZER <thunderbirdtr@fedoraproject.org>

### CODE REVIEW

**Comment by Prayag2** [comment]
I'm sorry I don't know much about CMAKE but could you please briefly describe what this is for?

**Comment by onuralpszr** [comment]
> I'm sorry I don't know much about CMAKE but could you please briefly describe what this is for?

I sent this initial cmake file for "installation" and also for linux distributions who wants to make "packaging" 

But the wider reason I sent this not just 2 things I said but using cmake advantages and gives more control over project such as version of the widget, using typescript or npm, plus I wanted to add translation section and control all of them from one location. 

I also wanted to use "qt_add_qml_module" side (still doing some experiement) for adding QML files to be recognize via qt-creator for people wants have IDE with nice QML control over it. 

Another point is in future If you need to access C++ side you can extend with cmake and do w/e needs to be done.

**Comment by Prayag2** [comment]
Oh, nice. I will merge both of your PRs after releasing 0.1.0.
I want to ship them in 0.2.0.

**Comment by Prayag2** [comment]
Merging it :)

**Comment by onuralpszr** [comment]
Time to start spamming more feature into your repo :)) Thanks again.

**Comment by Prayag2** [comment]
hehe :laughing:

**Pull request merged**
