### PR TITLE
feat: disable/Enable wifi switch and proper visual feedback controls

### LINKED ISSUE #20: [Feature request] WiFi on/off switch
It'd be good to be able to turn on/off wifi connection from panel. Also turned off devide (Wifi, bluetooth) could change icon color (turned on - color; turned off - black)

### PR DESCRIPTION
**Pull request by onuralpszr**
This is PR Fix : https://github.com/Prayag2/kde_controlcentre/issues/20

Check notes: https://github.com/Prayag2/kde_controlcentre/issues/20#issuecomment-1277254609
Final look: https://github.com/Prayag2/kde_controlcentre/issues/20#issuecomment-1277441782

Signed-off-by: Onuralp SEZER <thunderbirdtr@fedoraproject.org>

### CODE REVIEW

**Comment by Prayag2** [comment]
Thank you! I'll test it in a day or two and merge it.

**Comment by onuralpszr** [comment]
Good once this one done. I wanna start airplane mode next to it. So make it more complete

**Comment by Prayag2** [comment]
Okay :)

**Comment by Prayag2** [comment]
Works great!

**Comment by onuralpszr** [comment]
> Works great!

Thank you, I am glad you enjoy it.

**Pull request merged**
