### PR TITLE
Fix: Plasma 6 Support

### LINKED ISSUE #61: [BUG] Plasma 6 Support
**Describe the bug**
Plasmoid does not work on plasma 6

**To Reproduce**
1. Install on plasma 6

**Expected behavior**
Works on plasma 6

**Desktop (please complete the following information):**
Operating System: Garuda Linux 
KDE Plasma Version: 6.0.0
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.7.6-1-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

**Have you installed the following dependencies? (Yes/No)**
 - `kdeplasma-addons`: Yes 
 - `plasma-nm`: Yes
 - KDE Connect Yes

**Additional context**
https://develop.kde.org/docs/plasma/widget/porting_kf6/

### PR DESCRIPTION
**Pull request by SadColourfulHues**
Should resolve #61

### CODE REVIEW

**Comment by benmordecai** [comment]
Is there anything preventing this from being merged?

**Comment by Prayag2** [comment]
> Is there anything preventing this from being merged?

No, it's nothing. I was just busy this week so didn't get the time to look into the PR. I'll be busy for a few more days so please bear with me until then!

**Comment by benmordecai** [comment]
Checking in once more to see if this is ready to merge.

**Comment by Prayag2** [comment]
Thanks for the much needed contribution! Sorry to keep you waiting for so long :/

**Pull request merged**
