### PR TITLE
feat: Volume and brightness percentage values.

### PR DESCRIPTION
**Pull request by onuralpszr**
Related to : https://github.com/Prayag2/kde_controlcentre/issues/15

### CODE REVIEW

**Comment by Prayag2** [comment]
Hi, please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in the future :)

**Comment by onuralpszr** [comment]
> Hi, please use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in the future :)

I will okay :)

**Comment by onuralpszr** [comment]
I updated the commit message based on what you ask accordingly. Also could you please add "hacktoberfest-accepted" labels on this PR once you merged it. If you're okay with it.

**Comment by Prayag2** [comment]
Thanks you so much for the help :)

**Comment by onuralpszr** [comment]
> Thanks you so much for the help :)

You're welcome, I am having fun to use and develop as well. It need more work to do :) Thank you for Label as well !! :))

**Pull request merged**
